//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ayarlar
    {
        public int id { get; set; }
        public string site_logo { get; set; }
        public string site_baslik { get; set; }
        public string site_aciklama { get; set; }
        public string site_link { get; set; }
        public string site_sahip_mail { get; set; }
        public string site_mail_host { get; set; }
        public string site_mail_mail { get; set; }
        public Nullable<int> site_mail_port { get; set; }
        public string site_mail_sifre { get; set; }
    }
}
