//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bolum
    {
        public bolum()
        {
            this.ogrproes = new HashSet<ogrpro>();
            this.projes = new HashSet<proje>();
        }
    
        public int bolum_id { get; set; }
        public string bolum_ad { get; set; }
        public string bolum_kisa { get; set; }
    
        public virtual ICollection<ogrpro> ogrproes { get; set; }
        public virtual ICollection<proje> projes { get; set; }
    }
}
