//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogrenci
    {
        public ogrenci()
        {
            this.ogrproes = new HashSet<ogrpro>();
        }
    
        public int ogr_id { get; set; }
        public string ogr_isim { get; set; }
        public string ogr_kul { get; set; }
        public string ogr_sifre { get; set; }
        public string ogr_mail { get; set; }
        public Nullable<int> ogr_yetki { get; set; }
        public string ogr_yil { get; set; }
        public Nullable<int> ogr_arsiv { get; set; }
        public Nullable<int> ogr_alt { get; set; }
        public string ogr_code { get; set; }
    
        public virtual ICollection<ogrpro> ogrproes { get; set; }
    }
}
