//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ogrpro
    {
        public int ogrpro_id { get; set; }
        public Nullable<int> ogrpro_ogr { get; set; }
        public Nullable<int> ogrpro_proje { get; set; }
        public Nullable<int> ogrpro_bolum { get; set; }
        public Nullable<int> ogrpro_tur { get; set; }
        public Nullable<int> ogrpro_data { get; set; }
        public Nullable<int> ogrpro_resim { get; set; }
        public Nullable<int> ogrpro_arsiv { get; set; }
    
        public virtual bolum bolum { get; set; }
        public virtual ogrenci ogrenci { get; set; }
        public virtual proje proje { get; set; }
        public virtual tur tur { get; set; }
    }
}
