//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proje
    {
        public proje()
        {
            this.ogrproes = new HashSet<ogrpro>();
        }
    
        public int proje_id { get; set; }
        public string proje_isim { get; set; }
        public Nullable<int> proje_bolum { get; set; }
        public Nullable<int> proje_tur { get; set; }
        public string proje_sayi { get; set; }
        public string proje_yil { get; set; }
        public string proje_mail { get; set; }
        public Nullable<int> proje_data { get; set; }
        public Nullable<int> proje_ata { get; set; }
        public Nullable<int> proje_resim { get; set; }
        public string proje_detay { get; set; }
        public Nullable<int> proje_arsiv { get; set; }
    
        public virtual bolum bolum { get; set; }
        public virtual ICollection<ogrpro> ogrproes { get; set; }
        public virtual tur tur { get; set; }
    }
}
