//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjeTakip.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebProjeDBEntities : DbContext
    {
        public WebProjeDBEntities()
            : base("name=WebProjeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ayarlar> ayarlar { get; set; }
        public virtual DbSet<bolum> bolum { get; set; }
        public virtual DbSet<kullanici> kullanici { get; set; }
        public virtual DbSet<ogrenci> ogrenci { get; set; }
        public virtual DbSet<ogrpro> ogrpro { get; set; }
        public virtual DbSet<proje> proje { get; set; }
        public virtual DbSet<tur> tur { get; set; }
    }
}
